In [1]:
import numpy as np
import pandas as pd
scroes = np.random.randint(50, 100,size=(50,5))
scores_df = pd.DataFrame(scroes,
             columns=['國文', '英文', '數學', '地理', '歷史'],
             index=range(1,51))
scores_df
sum_values = scores_df.sum(axis=1)
mean_values = scores_df.mean(axis=1)
scores_df['總分'] = sum_values
scores_df['平均'] = mean_values

In [2]:
scores_df

    國文  英文  數學  地理  歷史   總分    平均
1   93  85  84  78  54  394  78.8
2   95  82  60  77  82  396  79.2
3   82  77  62  90  67  378  75.6
4   94  78  70  74  90  406  81.2
5   74  91  58  80  55  358  71.6
6   68  63  78  76  91  376  75.2
7   62  93  92  85  96  428  85.6
8   62  94  68  52  67  343  68.6
9   83  67  71  65  67  353  70.6
10  81  91  70  84  84  410  82.0
11  89  88  79  52  87  395  79.0
12  96  81  97  99  91  464  92.8
13  60  58  91  77  59  345  69.0
14  84  71  52  71  91  369  73.8
15  94  58  56  63  54  325  65.0
16  64  84  95  74  52  369  73.8
17  73  85  84  55  67  364  72.8
18  81  72  62  67  73  355  71.0
19  50  80  92  92  92  406  81.2
20  78  87  51  81  96  393  78.6
21  98  85  75  50  76  384  76.8
22  94  75  83  53  68  373  74.6
23  60  55  50  65  51  281  56.2
24  68  51  83  90  90  382  76.4
25  73  91  89  51  56  360  72.0
26  66  65  89  59  83  362  72.4
27  86  64  63  52  54  319  63.8
28  55  58  56  61  62  292  58.4
29  60  91  56  85  75  367  73.4
30  89  92  69  53  88  391  78.2
31  65  53  78  87  71  354  70.8
32  75  95  78  88  79  415  83.0
33  65  93  78  96  59  391  78.2
34  91  55  80  63  97  386  77.2
35  84  99  54  98  71  406  81.2
36  60  64  52  82  51  309  61.8
37  58  64  60  74  86  342  68.4
38  79  95  97  74  86  431  86.2
39  89  99  88  51  90  417  83.4
40  89  74  91  95  99  448  89.6
41  66  95  55  75  71  362  72.4
42  80  96  95  84  69  424  84.8
43  87  98  58  65  92  400  80.0
44  59  56  86  86  70  357  71.4
45  86  75  88  87  56  392  78.4
46  98  92  79  58  50  377  75.4
47  78  77  70  76  77  378  75.6
48  76  55  75  71  70  347  69.4
49  81  86  99  71  65  402  80.4
50  96  98  51  66  77  388  77.6

In [4]:
#總分由小到大sort_values  ascemding=false指由大到小 iloc[:5]前五比
scores_df.sort_values(by='總分',ascending=False).iloc[:5]
#scores_df.sort_values(by='總分').iloc[:5]

    國文  英文  數學  地理  歷史   總分    平均
23  60  55  50  65  51  281  56.2
28  55  58  56  61  62  292  58.4
36  60  64  52  82  51  309  61.8
27  86  64  63  52  54  319  63.8
15  94  58  56  63  54  325  65.0

In [5]:
#使用subscript[],過濾資料
scores_df[scores_df['平均'] < 80]

    國文  英文  數學  地理  歷史   總分    平均
1   93  85  84  78  54  394  78.8
2   95  82  60  77  82  396  79.2
3   82  77  62  90  67  378  75.6
5   74  91  58  80  55  358  71.6
6   68  63  78  76  91  376  75.2
8   62  94  68  52  67  343  68.6
9   83  67  71  65  67  353  70.6
11  89  88  79  52  87  395  79.0
13  60  58  91  77  59  345  69.0
14  84  71  52  71  91  369  73.8
15  94  58  56  63  54  325  65.0
16  64  84  95  74  52  369  73.8
17  73  85  84  55  67  364  72.8
18  81  72  62  67  73  355  71.0
20  78  87  51  81  96  393  78.6
21  98  85  75  50  76  384  76.8
22  94  75  83  53  68  373  74.6
23  60  55  50  65  51  281  56.2
24  68  51  83  90  90  382  76.4
25  73  91  89  51  56  360  72.0
26  66  65  89  59  83  362  72.4
27  86  64  63  52  54  319  63.8
28  55  58  56  61  62  292  58.4
29  60  91  56  85  75  367  73.4
30  89  92  69  53  88  391  78.2
31  65  53  78  87  71  354  70.8
33  65  93  78  96  59  391  78.2
34  91  55  80  63  97  386  77.2
36  60  64  52  82  51  309  61.8
37  58  64  60  74  86  342  68.4
41  66  95  55  75  71  362  72.4
44  59  56  86  86  70  357  71.4
45  86  75  88  87  56  392  78.4
46  98  92  79  58  50  377  75.4
47  78  77  70  76  77  378  75.6
48  76  55  75  71  70  347  69.4
50  96  98  51  66  77  388  77.6

In [10]:
#平均80以下,歷史不及格的
#scores_df[{scores_df['平均'] < 80} & {scores_df['歷史'] < 60}]
scores_df[(scores_df['平均'] < 80) & (scores_df['歷史'] < 60)]

    國文  英文  數學  地理  歷史   總分    平均
1   93  85  84  78  54  394  78.8
5   74  91  58  80  55  358  71.6
13  60  58  91  77  59  345  69.0
15  94  58  56  63  54  325  65.0
16  64  84  95  74  52  369  73.8
23  60  55  50  65  51  281  56.2
25  73  91  89  51  56  360  72.0
27  86  64  63  52  54  319  63.8
33  65  93  78  96  59  391  78.2
36  60  64  52  82  51  309  61.8
45  86  75  88  87  56  392  78.4
46  98  92  79  58  50  377  75.4

In [11]:
scores_df.query('平均<80 and 歷史<60')

    國文  英文  數學  地理  歷史   總分    平均
1   93  85  84  78  54  394  78.8
5   74  91  58  80  55  358  71.6
13  60  58  91  77  59  345  69.0
15  94  58  56  63  54  325  65.0
16  64  84  95  74  52  369  73.8
23  60  55  50  65  51  281  56.2
25  73  91  89  51  56  360  72.0
27  86  64  63  52  54  319  63.8
33  65  93  78  96  59  391  78.2
36  60  64  52  82  51  309  61.8
45  86  75  88  87  56  392  78.4
46  98  92  79  58  50  377  75.4